server:
    port: 8020

eureka:
    client:
        serviceUrl:
            defaultZone: http://180.100.223.110:8010/eureka/
#            多注册中心配置
#            defaultZone: http://180.100.223.110:8010/eureka/,http://180.100.223.110:7010/eureka/

spring:
    application:
        name: eureka-client
