server:
    port: 8020

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8010/eureka/
#            多注册中心配置
#            defaultZone: http://localhost:8010/eureka/,http://localhost:7010/eureka/

spring:
    application:
        name: eureka-client
