eureka:
  client:
    serviceUrl:
      defaultZone: http://180.100.223.110:8080/eureka/

server:
  port: 8070

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shadowFirst/springCloud.git
          searchPaths: spring-cloud/helloworldConfig
  application:
    name: config-server