eureka:
  client:
    serviceUrl:
      defaultZone: http://180.100.223.110:8010/eureka/

server:
  port: 8030

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hzz-shadow/SpringCloudLearning
#          根目录不需要该属性
          searchPaths: /**
  application:
    name: config-server