eureka:
  client:
    serviceUrl:
      defaultZone: http://180.100.223.110:8010/eureka/

server:
  port: 8030

spring:
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/hzz-shadow/SpringCloudLearning/
          search-locations: properties
          username: 1547275544@qq.com
          password: hzzshadow3429

  application:
    name: config-server