eureka:
  client:
    serviceUrl:
      defaultZone: http://180.100.223.110:8080/eureka/

server:
  port: 8070

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hzz-shadow/SpringCloudLearning.git
#          根目录不需要该属性
#          searchPaths:
  application:
    name: config-server