eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

server:
  port: 8030

spring:
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/hzz-shadow/SpringCloudLearning
          search-paths: config-properties
          username: hzz-shadow
          password: hzzshadow3429

  application:
    name: config-server
